version: '3.4'

services:
  dockerfilesamples:
    image: dockerfilesamples
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 80:80
      - 5005:5005
