version: '3.4'

services:
  dockerfilesamples:
    image: dockerfilesamples
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 app.py runserver 0.0.0.0:80 --nothreading --noreload"]
    ports:
      - 80:80
      - 5678:5678
